CREATE TABLE posts(
    id VARCHAR(36) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    note VARCHAR(1024) NOT NULL,
    body VARCHAR(12800) NOT NULL,
    posted_on DATETIME DEFAULT CURRENT_TIMESTAMP
);